import Head from "next/head";
import { NextPage } from "next";
import PersonItem from "components/PersonItem/PersonItem";
import Features from "components/Features/Features";
import Header from "components/Header/Header";
import Featured from "components/Featured/Featured";
import TrustedBy from "components/TrustedBy/TrustedBy";
import ProjectsItem from "components/ProjectsItem/ProjectsItem";
import Carousel from "components/Carousel/Carousel";
import Explore from "components/Explore/Explore";
import { IProject, ICard, cards, projects, persons } from "data";
import ServiceItem from "components/ServiceItem/ServiceItem";
import FeaturesDark from "components/FeaturesDark/FeaturesDark";
import LogoMaker from "components/LogoMaker/LogoMaker";
import Footer from "components/Footer/Footer";
import style from "./styles/main.module.scss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Copy fiver</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <Header />
          <Featured />
          <TrustedBy />
          <div className={style.carouselWrapper}>
            <h2 className={style.carouselTitle}>
              Popular professional services
            </h2>
            <Carousel
              slidesToShow={{
                wideDesktop: 5,
                desktop: 4,
                tablet: 3,
                smallTablet: 2,
                mobile: 1,
              }}
            >
              {cards.map((item: ICard, index: number) => {
                return (
                  <div key={index + item.title} className={style.itemBox}>
                    <ServiceItem
                      path={item.path}
                      img={item.img}
                      title={item.title}
                      desc={item.desc}
                      id={item.id}
                    />
                  </div>
                );
              })}
            </Carousel>
          </div>
          <Features />
          <Explore />
          <FeaturesDark />
          <div className={style.carouselWrapper}>
            <Carousel
              slidesToShow={{
                wideDesktop: 1,
                desktop: 1,
                tablet: 1,
                smallTablet: 1,
                mobile: 1,
              }}
            >
              {persons.map((item, index) => {
                return (
                  <PersonItem
                    key={item.name + index}
                    video={item.video}
                    poster={item.poster}
                    name={item.name}
                    profession={item.profession}
                    quote={item.qoute}
                  />
                );
              })}
            </Carousel>
          </div>

          <LogoMaker />
          <div className={style.carouselWrapper}>
            <Carousel
              slidesToShow={{
                wideDesktop: 4,
                desktop: 3,
                tablet: 2,
                smallTablet: 2,
                mobile: 1,
              }}
            >
              {projects.map((item: IProject) => {
                return (
                  <div key={item.id + item.username}>
                    <ProjectsItem
                      img={item.img}
                      linkPath={"#"}
                      avatar={item.pp}
                      userName={item.username}
                      category={item.cat}
                      quote={item.quote}
                    />
                  </div>
                );
              })}
            </Carousel>
          </div>
          <Footer />
        </div>
      </main>
    </>
  );
};

export default Home;
